INPUT_SHAPE = (60, 82)
NUM_OF_FEATURE_MAP = 8
KERNEL_SIZE = 3
POOL_SIZE = 2
DENSE_UNITS = 104

ALL_COLS = ['AAPL',
            'AMZN',
            'AUD',
            'Brent',
            'CAC-F',
            'CAD',
            'CHF',
            'CNY',
            'CTB1Y',
            'CTB3M',
            'CTB6M',
            'Close',
            'DAAA',
            'DAX-F',
            'DBAA',
            'DE1',
            'DE2',
            'DE4',
            'DE5',
            'DE6',
            'DGS10',
            'DGS5',
            'DJI',
            'DJI-F',
            'DTB3',
            'DTB4WK',
            'DTB6',
            'Date',
            'Dollar index',
            'Dollar index-F',
            'EMA_10',
            'EMA_20',
            'EMA_200',
            'EMA_50',
            'EUR',
            'FCHI',
            'FTSE',
            'FTSE-F',
            'GAS-F',
            'GBP',
            'GDAXI',
            'GE',
            'GSPC',
            'Gold',
            'HSI',
            'HSI-F',
            'IXIC',
            'JNJ',
            'JPM',
            'JPY',
            'KOSPI-F',
            'MSFT',
            'NASDAQ-F',
            'NYSE',
            'NZD',
            'Name',
            'Nikkei-F',
            'Oil',
            'ROC_10',
            'ROC_15',
            'ROC_20',
            'ROC_5',
            'RUSSELL-F',
            'RUT',
            'S&P',
            'S&P-F',
            'SSEC',
            'TE1',
            'TE2',
            'TE3',
            'TE5',
            'TE6',
            'Volume',
            'WFC',
            'WIT-oil',
            'XAG',
            'XAU',
            'XOM',
            'copper-F',
            'gold-F',
            'mom',
            'mom1',
            'mom2',
            'mom3',
            'silver-F',
            'wheat-F']
